from pathlib import Path
exec((Path.cwd()/'tests'/'browser_checks.py').read_text(encoding='utf-8').split('\nstart()')[0],globals())
group=os.environ.get('QA_GROUP','advanced')
start()
def until(expression,seconds=4):
    at=time.monotonic()
    while time.monotonic()-at<seconds:
        if js(expression): return True
        time.sleep(.035)
    return False
def bring(selector):
    js("document.querySelector("+json.dumps(selector)+").scrollIntoView({block:'center'})")
    time.sleep(.03);click(selector)
if group=='advanced':
    view(844,390);time.sleep(.1)
    for phase in range(5):
        js("Tsukikage.start({seed:12345});window.finishedCount=0")
        original=js('JSON.stringify(Tsukikage.snapshot())')
        js("Tsukikage.visuals.play(Tsukikage.visuals.sample({tier:'mangan'}),()=>window.finishedCount++,{demo:true})")
        check('phase '+str(phase)+' becomes observable',until("document.getElementById('winScene').dataset.phase==="+json.dumps(str(phase))))
        shot('scene-phase-'+str(phase))
        js("Tsukikage.visuals.skip();Tsukikage.visuals.skip()")
        check('skip at phase '+str(phase)+' cleans up once',js("finishedCount===1&&!Tsukikage.visuals.active&&!document.querySelector('.app').inert&&!document.getElementById('sceneBody')"))
        check('phase '+str(phase)+' preview preserves state',original==js('JSON.stringify(Tsukikage.snapshot())'))
    for label in ['mangan','haneman','baiman','sanbaiman','yakuman']:
        data=js("(()=>{let r=Tsukikage.visuals.sample({tier:"+json.dumps(label)+",character:2});return{tier:Tsukikage.visuals.tier(r.winners[0].score),han:r.winners[0].score.han,limit:r.winners[0].score.limit,unique:new Set(r.indicators).size,count:r.indicators.length}})()")
        check('legal preview '+label,data['tier']==label and data['unique']==data['count'] and data['count']<=5,data)
    js("Tsukikage.start({seed:12345})")
    fixture(['123456m55789p23s','777888m666s555z4s9m','123456m55789p23s'])
    js("{let g=Tsukikage.game;g.current=1;let id=g.players[1].hand.find(x=>Riichi.type(x)===21);g.players[1].drawn=id;g.discard(1,id);g.resolve({kind:'ron'})}")
    paid=js('Tsukikage.game.points.slice()')
    check('double ron first winner shown',until("document.querySelector('#sceneBody h2')?.textContent===Characters.names[2]"))
    check('double ron second winner shown',until("document.querySelector('#sceneBody h2')?.textContent===Characters.names[0]"))
    js("Tsukikage.visuals.skip();Tsukikage.visuals.skip()")
    check('double ron has both details and one settlement',js("document.querySelectorAll('.result-person').length===2&&Tsukikage.game.result.winners.length===2") and paid==js('Tsukikage.game.points'))
    shot('double-ron-result')
    js("Tsukikage.start({seed:12345})")
    fixture(['123456m55789p234s','22s123p789m55566z'])
    js("{let g=Tsukikage.game,id=g.players[0].hand.find(x=>Riichi.type(x)===19);g.discard(0,id,true);g.pending.cpu={1:g.pending.choices[1].find(x=>x.kind==='pon')};g.resolve()}")
    check('called riichi tile retains sideways slot and badge',js("Tsukikage.game.players[0].river[0].called&&Tsukikage.game.sticks===1&&Tsukikage.game.points[0]===24000&&!!document.querySelector('#river0 .sideways-slot .called.riichi-tile')&&!!document.querySelector('#selfInfo .tenpai')"))
    js("Tsukikage.game.assertIntegrity()")
elif group=='storage':
    view(1366,768)
    original=js('Tsukikage.snapshot()')
    js('location.reload()');time.sleep(.2);wait_for_load();bring('[data-act="restore"]')
    restored=js('Tsukikage.snapshot()')
    check('saved hand wall score and RNG restore',all(original[k]==restored[k] for k in ['players','wall','dead','points','rngState','phase']))
    js('Tsukikage.showSettings()')
    js("document.getElementById('v3-helperLabels').checked=false;document.getElementById('v3-actualDora').checked=false;document.getElementById('v3-guideLevel').value='request'")
    bring('[data-act="save-settings"]');js('location.reload()');time.sleep(.2);wait_for_load()
    check('independent preferences persist',js("!Tsukikage.prefs.helperLabels&&!Tsukikage.prefs.actualDora&&Tsukikage.prefs.guideLevel==='request'&&Tsukikage.prefs.recommend"))
    js("localStorage.removeItem('tsukikage-riichi-prefs-v3');localStorage.setItem('tsukikage-riichi-prefs-v1',JSON.stringify({riichiAuto:true,tileTheme:'ivory'}));location.reload()");time.sleep(.2);wait_for_load()
    check('v1 automatic discard does not migrate on',js("!Tsukikage.prefs.riichiAuto&&Tsukikage.prefs.tileTheme==='ivory'&&JSON.parse(localStorage.getItem('tsukikage-riichi-prefs-v1')).riichiAuto"))
    js("let prior=JSON.parse(localStorage.getItem('tsukikage-riichi-state-v3'));localStorage.setItem('tsukikage-riichi-state-v1',JSON.stringify({schema:1,state:prior.state}));localStorage.removeItem('tsukikage-riichi-state-v3');window.legacyText=localStorage.getItem('tsukikage-riichi-state-v1')")
    legacy=js("localStorage.getItem('tsukikage-riichi-state-v1')")
    js('location.reload()');time.sleep(.2);wait_for_load();bring('[data-act="restore"]')
    check('v1 game migration preserves original key',legacy==js("localStorage.getItem('tsukikage-riichi-state-v1')") and js("Tsukikage.game.assertIntegrity()&&Tsukikage.game.phase==='turn'"))
    bad=json.dumps({'schema':3,'state':{'phase':'turn','players':[],'points':[25000]*4}})
    injection=cdp('Page.addScriptToEvaluateOnNewDocument',source="localStorage.setItem('tsukikage-riichi-state-v3',"+json.dumps(bad)+")")
    js("location.reload()");time.sleep(.2);time.sleep(.2);wait_for_load()
    cdp('Page.removeScriptToEvaluateOnNewDocument',identifier=injection['identifier'])
    bring('[data-act="restore"]')
    check('invalid save rejected with original retained',js("localStorage.getItem('tsukikage-riichi-state-v3')")==bad and js("document.getElementById('notice').textContent.includes('불러올 수 없어')"))
    js("localStorage.clear();location.reload()");time.sleep(.2);wait_for_load()
    js("Storage.prototype.setItem=function(){throw new DOMException('Denied','SecurityError')};Tsukikage.start({seed:12345})")
    check('storage denial leaves playable hand',js("document.getElementById('saveStatus').textContent.includes('불가')&&!!document.querySelector('#handRow button:not(:disabled)')"))
    js('location.reload()');time.sleep(.2);wait_for_load()
elif group=='errors':
    view(844,390)
    cdp('Network.enable');cdp('Network.setCacheDisabled',cacheDisabled=True);cdp('Network.setBlockedURLs',urls=['*assets/characters/*','*assets/audio/*'])
    js("location.reload()");time.sleep(.2);wait_for_load();js("Tsukikage.start({seed:12345})")
    time.sleep(.3)
    check('missing character assets keep readable scores and legal controls',js("document.getElementById('seat1').textContent.includes('아카네')&&document.getElementById('selfInfo').textContent.includes('25,000')&&!!document.querySelector('#handRow button:not(:disabled)')"))
    click('#soundBtn')
    target=js("document.querySelector('#handRow button:not(:disabled)').getAttribute('data-tile')")
    click('[data-tile="'+target+'"]');time.sleep(.1);click('[data-tile="'+target+'"]')
    check('missing audio does not block discard',js("Tsukikage.game.players[0].river.length===1"))
    cdp('Network.setBlockedURLs',urls=[]);cdp('Network.setCacheDisabled',cacheDisabled=False)
    js("Tsukikage.start({seed:12345})")
    cdp('Emulation.setEmulatedMedia',features=[{'name':'prefers-reduced-motion','value':'reduce'}])
    js("window.fxDone=0;Tsukikage.visuals.play(Tsukikage.visuals.sample(),()=>window.fxDone++,{demo:true})")
    check('reduced motion immediately finishes without lock',js("fxDone===1&&!Tsukikage.visuals.active&&!document.querySelector('.app').inert"))
    cdp('Emulation.setEmulatedMedia',features=[{'name':'prefers-reduced-motion','value':'no-preference'}])
    js("localStorage.setItem('tsukikage-riichi-prefs-v3',JSON.stringify({guideLevel:'tutorial'}));location.reload()");time.sleep(.2);wait_for_load();js("Tsukikage.start({seed:12345})")
    frozen=js('JSON.stringify(Tsukikage.snapshot())');time.sleep(.3)
    check('tutorial pauses exact state',js("document.getElementById('modalCard').dataset.modalType==='tutorial'") and frozen==js('JSON.stringify(Tsukikage.snapshot())'))
    bring('[data-act="close-modal"]')
    check('tutorial resumes same human turn',js("Tsukikage.game.current===0&&Tsukikage.game.phase==='turn'&&document.getElementById('modal').hidden"))
elif group=='cancel':
    view(1366,768)
    for kind in ['resize','modal','turn','escape','blur']:
        js("Tsukikage.start({seed:12345})");fixture(['555m123p456s789m11z'])
        a=rect('[data-tile="16"]');b=rect('#discardZone')
        cdp('Input.dispatchMouseEvent',type='mousePressed',x=a['x'],y=a['y'],button='left',clickCount=1)
        with ThreadPoolExecutor(max_workers=1) as pool:
            movement=pool.submit(cdp,'Input.dispatchMouseEvent',type='mouseMoved',x=b['x'],y=b['y'],button='none',buttons=1)
            check(kind+' starts real drag',until("!!document.querySelector('.drag-ghost')"))
            if kind=='resize': view(844,390)
            elif kind=='modal': js('Tsukikage.showSettings()')
            elif kind=='turn': js("Tsukikage.game.version++;Tsukikage.game.current=1;Tsukikage.render()")
            elif kind=='escape': cdp('Input.dispatchKeyEvent',type='keyDown',key='Escape',code='Escape',windowsVirtualKeyCode=27)
            else: js("dispatchEvent(new Event('blur'))")
            cdp('Input.dispatchMouseEvent',type='mouseReleased',x=b['x'],y=b['y'],button='left',clickCount=1)
            movement.result(timeout=8)
        check(kind+' cancels without discard or ghost',js("Tsukikage.game.players[0].river.length===0&&!document.querySelector('.drag-ghost')"))
        if kind=='modal': bring('[data-act="close-modal"]')
        view(1366,768);time.sleep(.5)
    view(390,844)
    check('portrait suggests rotation and settings stay accessible',js("getComputedStyle(document.querySelector('.rotate-note')).display!=='none'&&!!document.getElementById('settingsBtn')"))
elif group=='delivery':
    view(1366,768)
    loaded=js("Promise.all(Characters.manifest.characters.flatMap(c=>[c.base,c.cutin,c.special,...Object.values(c.expressions)]).map(src=>new Promise(resolve=>{let i=new Image();i.onload=()=>resolve({src,ok:i.naturalWidth>0});i.onerror=()=>resolve({src,ok:false});i.src=src})))")
    check('all forty production images load',len(loaded)==40 and all(x['ok'] for x in loaded),loaded)
    audio=js("Promise.all(Object.values(Characters.manifest.audio).map(src=>new Promise(resolve=>{let a=new Audio(src);a.onloadedmetadata=()=>resolve({src,duration:a.duration});a.onerror=()=>resolve({src,duration:0})})))")
    check('seven WAV files decode with real durations',len(audio)==7 and all(x['duration']>0 for x in audio),audio)
    js("Tsukikage.start({seed:12345});Tsukikage.game.current=1;Tsukikage.pause(false);Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))")
    before=js('JSON.stringify(Tsukikage.snapshot())');time.sleep(.5)
    check('background visibility event cancels CPU reservation',before==js('JSON.stringify(Tsukikage.snapshot())'))
    js("Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});document.dispatchEvent(new Event('visibilitychange'))")
    check('return visibility event resumes CPU flow',until('JSON.stringify(Tsukikage.snapshot())!=='+json.dumps(before),3))
    new_tab((ROOT/'dist'/'index.html').resolve().as_uri());activate_tab(current_tab());wait_for_load()
    js("Tsukikage.start({seed:12345})");time.sleep(.3)
    check('file URL build is playable with local images',js("Tsukikage.game.phase==='turn'&&document.querySelectorAll('#handRow button[data-tile]').length===14&&[...document.images].every(i=>i.complete&&i.naturalWidth>0)"))
    shot('file-url-build')
elif group=='readability':
    view(1366,768)
    js("document.querySelector('#wallHud [data-public-tile]').focus()")
    check('public indicator focus opens enlarged face',js("!document.getElementById('tileInspect').hidden&&document.querySelectorAll('.public-match').length>0"))
    check('public match highlight is one exact tile type',js("new Set([...document.querySelectorAll('.public-match')].map(e=>e.dataset.faceType)).size===1"))
    view(844,390,True)
    cdp('Input.dispatchKeyEvent',type='keyDown',key='Escape',code='Escape',windowsVirtualKeyCode=27)
    b=rect('#wallHud [data-public-tile]')
    cdp('Input.dispatchTouchEvent',type='touchStart',touchPoints=[{'x':b['x'],'y':b['y'],'id':1}]);time.sleep(.6)
    check('public long touch enlarges without discarding',js("!document.getElementById('tileInspect').hidden&&Tsukikage.game.players[0].river.length===0"))
    cdp('Input.dispatchTouchEvent',type='touchEnd',touchPoints=[])
    view(1366,768);js("Tsukikage.showSettings();document.getElementById('v3-helperLabels').checked=false;document.getElementById('v3-actualDora').checked=false;document.getElementById('v3-recommend').checked=true")
    bring('[data-act="save-settings"]')
    check('helper and actual dora off preserve recommendations',js("document.documentElement.dataset.helperLabels==='off'&&document.documentElement.dataset.actualDora==='off'&&Tsukikage.prefs.recommend&&document.querySelector('.recommend-info .overline').textContent.includes('추천')"))
(OUT/('browser-'+group+'.json')).write_text(json.dumps({'runAt':time.strftime('%Y-%m-%dT%H:%M:%S%z'),'browser':'isolated Chromium CDP','checks':results},ensure_ascii=False,indent=2),encoding='utf-8')
print(str(len(results))+' checks complete for '+group)
